app:
  date_format: '%Y-%m-%d'
  enable_console_logging: true
  enable_file_logging: true
  log_backup_count: 5
  log_file_max_size: 10
  log_format: detailed
  log_level: INFO
  max_workers: 4
cli:
  elevation: false
  extract_waypoints: false
  input: ''
  min_dist: 17
  output: ''
gui:
  auto_scroll_log: true
  log_window_height: 200
  max_log_lines: 1000
  theme: light
  window_height: 600
  window_width: 800
misc:
  some_color:
  - 255
  - 0
  - 0
  some_date: '2025-06-23T18:08:00'
  some_file: some_file.txt
